### ISSUE TITLE
Admin Interface GUI

### ISSUE THREAD

**Issue by HyperCriSiS** [YunoHost-Apps/wireguard_ynh#1]
Hi,

I think there is a better Admin Interface GUI available:
https://github.com/subspacecommunity/subspace

What do you think?

Regards,
Hyper

**Comment by tituspijean** [comment]
I am definitely open to changing GUIs, but I need some arguments in favor. ;)

**Comment by jlopez777** [comment]
I love that you are open to the change, however, as a noob, I really like the clean interface of the one chosen. Clean, simple, and it seems way more manageable for newer users to the space.

**Comment by dumprop** [comment]
> 
> 
> I am definitely open to changing GUIs, but I need some arguments in favor. ;) And a way to transfer the configuration too...

It seems more well maintained w/ slack chat support
![image](https://user-images.githubusercontent.com/34004367/125734218-5b36bad7-ee48-4850-8cb2-dd1c2ec00fb8.png)
![image](https://user-images.githubusercontent.com/34004367/125734244-0c800a0f-f5ca-46bd-8aec-f7acc96ca12e.png)
Also it more secure thanks to [sonar in CI/CD](https://sonarcloud.io/dashboard?id=subspacecommunity_subspace), SSO
May not need to configure post up/down script (Im not sure)
So, I like it
Migrating the configuration is questionable. I would personally do without it. Just uninstall current and would have installed a new one
