### ISSUE TITLE
I can't start wireguard.service 

### ISSUE THREAD

**Issue by L-S-2020** [YunoHost-Apps/wireguard_ynh#15]
Hello, I have a problem with the Wireguard service. 

### Describe the bug
I've just installed Wireguard, but I can't start Wireguard.service. Here the logs:
https://paste.yunohost.org/ogiyuyidiy

### Context

- Hardware: *VPS bought online
- YunoHost version: 4.1.7.3
- I have access to my server: *Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no

### Steps to reproduce
I've installed Wireguard through the webadmin, the installation has worked, but on the service status page the service is failed, I tried to restart, but that don't work. 

### Logs

https://paste.yunohost.org/ogiyuyidiy

I hope you can help me.

**Comment by tituspijean** [comment]
@L-S-2020 thanks for your feedback.
As hinted by the error log, can you run the following command and report its output here?

```bash
systemctl status wg-quick@wg0.service
```

**Comment by L-S-2020** [comment]
@tituspijean thank you for your quick answer, here the output from systemctl status wg-quick@wg0.service:

● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; disabled; vendor prese
   Active: failed (Result: exit-code) since Sun 2021-03-07 10:24:55 CET; 4h 45mi
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
 Main PID: 8816 (code=exited, status=0/SUCCESS)

Mar 07 09:54:56 domain.tld wg-quick[8816]: [#] ip -4 address add 10.10.10.0/24 de
Mar 07 09:54:56 domain.tld wg-quick[8816]: [#] ip link set mtu 1450 up dev wg0
Mar 07 09:54:56 domain.tld wg-quick[8816]: [#]
Mar 07 09:54:56 domain.tld systemd[1]: Started WireGuard via wg-quick(8) for wg0.
Mar 07 10:24:55 domain.tld systemd[1]: Stopping WireGuard via wg-quick(8) for wg0
Mar 07 10:24:55 domain.tld wg-quick[19797]: /usr/bin/wg-quick: line 346: wg: comm
Mar 07 10:24:55 domain.tld wg-quick[19797]: wg-quick: `wg0' is not a WireGuard in
Mar 07 10:24:55 domain.tld systemd[1]: wg-quick@wg0.service: Control process exit
Mar 07 10:24:55 domain.tld systemd[1]: wg-quick@wg0.service: Failed with result '
Mar 07 10:24:55 domain.tld systemd[1]: Stopped WireGuard via wg-quick(8) for wg0.
lines 1-21/21 (END)...skipping...
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-03-07 10:24:55 CET; 4h 45min ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
 Main PID: 8816 (code=exited, status=0/SUCCESS)

Mar 07 09:54:56 domain.tld wg-quick[8816]: [#] ip -4 address add 10.10.10.0/24 dev wg0
Mar 07 09:54:56 domain.tld wg-quick[8816]: [#] ip link set mtu 1450 up dev wg0
Mar 07 09:54:56 domain.tld wg-quick[8816]: [#]
Mar 07 09:54:56 domain.tld systemd[1]: Started WireGuard via wg-quick(8) for wg0.
Mar 07 10:24:55 domain.tld systemd[1]: Stopping WireGuard via wg-quick(8) for wg0...
Mar 07 10:24:55 domain.tld wg-quick[19797]: /usr/bin/wg-quick: line 346: wg: command not found
Mar 07 10:24:55 domain.tld wg-quick[19797]: wg-quick: `wg0' is not a WireGuard interface
Mar 07 10:24:55 domain.tld systemd[1]: wg-quick@wg0.service: Control process exited, code=exited, status=1/FAILURE
Mar 07 10:24:55 domain.tld systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
Mar 07 10:24:55 domain.tld systemd[1]: Stopped WireGuard via wg-quick(8) for wg0.

**Comment by tituspijean** [comment]
What about 

```
systemctl status wireguard
```

Have you rebooted your server after the installation?
Have you clicked on "Apply config" in WireGuard' webapp?

**Comment by L-S-2020** [comment]
Here the logs:
wireguard.service - WireGuard restart
   Loaded: loaded (/etc/systemd/system/wireguard.service; static; vendor preset: enabled)
   Active: inactive (dead)

**Comment by L-S-2020** [comment]
Here the logs:
● wireguard.service - WireGuard restart
   Loaded: loaded (/etc/systemd/system/wireguard.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-03-07 15:24:40 CET; 18s ago
  Process: 3083 ExecStart=/bin/systemctl restart wg-quick@wg0.service (code=exited, status=4)
 Main PID: 3083 (code=exited, status=4)

Mar 07 15:24:40 domain.tld systemd[1]: Starting WireGuard restart...
Mar 07 15:24:40 domain.tld systemctl[3083]: Failed to restart wg-quick@wg0.service: Access denied
Mar 07 15:24:40 domain.tld systemctl[3083]: See system logs and 'systemctl status wg-quick@wg0.service' for details.
Mar 07 15:24:40 domain.tld systemd[1]: wireguard.service: Main process exited, code=exited, status=4/NOPERMISSION
Mar 07 15:24:40 domain.tld systemd[1]: wireguard.service: Failed with result 'exit-code'.
Mar 07 15:24:40 domain.tld systemd[1]: Failed to start WireGuard restart.

**Comment by L-S-2020** [comment]
I've solved the problem.
1. You're right I forgot to click at "Apply config".
2. I've edited the file /etc/systemd/system/wireguard.service and replaced user und group "wireguard" with "root".
Thanks for your help, now it works
