### ISSUE TITLE
Port 8095 not available even if open

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/wireguard_ynh#24]
### Describe the bug

Port 8095 appears to be unavailable even if my server provider (Contabo) tells me it is open and I clearly see it is in the list of opened ports in the Yunohost firewall.

This is the error message I get:

![Screenshot 2021-05-27 at 6 08 10 PM](https://user-images.githubusercontent.com/42862428/122669828-98065a80-d1ae-11eb-8e59-422e54b863ff.png)

### Context

**Hardware**: Contabo VPS
**YunoHost version**: 4.2.6
**I have access to my server**: SSH and browser
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?**: no

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install wireguard
    ```
- Setting up a profile and trying to use it on a client

### Expected behavior

After installing the app and setting its configuration, the connection should work, but it does not.

### Logs

Unfortunately, I do not know how to access WireGuard-specific logs.

**Comment by tituspijean** [comment]
Hello,

Can you clarify (there is slight change between your bug description and expected behavior): do you have access to your WireGuard network?

If yes, as already discussed there https://forum.yunohost.org/t/port-8095-not-available-even-if-open-wireguard/16022 with you, the port being displayed as not opened is most likely an issue in the diagnosis system of YunoHost. There is not much I can do here, but I will keep the issue open while it is resolved upstream.

If not, please share your WireGuard service logs (in the webadmin), and share the results of `wg` command (hide any public, private, shared key [this is critical]).

**Comment by xplosionmind** [comment]
Thanks a lot for your help, @tituspijean.

To be completely honest, I never used WireGuard before, so I cannot be completely certain that my inability to connect to my WireGuard network installed on my Yunohost instance is due to a bug and not because of my wrong configuration settings.

I would paste below the results of the `wg` command, as I already did in the forum, but now I have a new problem. I get this when trying to visit my web WireGuard client:

<img width="1440" alt="Screenshot 2021-06-24 at 8 18 17 AM" src="https://user-images.githubusercontent.com/42862428/123212170-f9327480-d4b3-11eb-8dc8-081ee1d5eb58.png">


Furthermore, by running the `wg` command via SSH, I get nothing, literally. It happens tha same it would happen if I typed CTRL+C…

I am starting to get crazy 🤯.

In any case, since you suggested to stick to one support venue, should we continue here or in the forum post you linked?

**Comment by xplosionmind** [comment]
Hello… is there any news?

**Comment by tituspijean** [comment]
Can you share the outputs of the following commands?

`sudo ls -la /opt/yunohost/wireguard`
`sudo ls -la /etc/wireguard`
`sudo wg-quick up wg0`
`systemctl restart wireguard_ui`
(and if it fails)
`journalctl -xe` (only the relevant parts about Wireguard's UI)

**Comment by xplosionmind** [comment]
Premise: sorry for pressing and asking for help and updates. I really need a self-hosted VPN and I am struggling without it.

> sudo ls -la /opt/yunohost/wireguard

```
drwxr-x--- 3 wireguard wireguard     4096 Jul  3 17:38 db
-rwxr-xr-x 1 root      root      22773423 Oct 10  2020 wireguard-ui
```

<br>

> sudo ls -la /etc/wireguard

```
-rw-r--r--   1 wireguard wireguard  366 Jul  3 17:38 wg0.conf
```

<br>

> sudo wg-quick up wg0

```
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.10.10.0/24 dev wg0
[#] ip link set mtu 1450 up dev wg0
[#]
```

<br>

> systemctl restart wireguard_ui

At first, failed because of denied access:
```
Failed to restart wireguard_ui.service: Access denied
See system logs and 'systemctl status wireguard_ui.service' for details.
```

then, prepending `sudo`, it worked

<br>

> journalctl -xe

```
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.
```

**Comment by tituspijean** [comment]
> Premise: sorry for pressing and asking for help and updates. I really need a self-hosted VPN and I am struggling without it.

No problem, really. I may express annoyment though, but it is not directed at you or other users. I am by no means an expert on WireGuard and networking, so testing and debugging is pretty much trial and error. And it can get very frustrating.

> -rwxr-xr-x 1 root      root      22773423 Oct 10  2020 wireguard-ui

OK so, maybe the binary not belonging to the `wireguard` user is an issue. Try `sudo chown wireguard:wireguard /opt/yunohost/wireguard/wireguard_ui`

> -rw-r--r--   1 wireguard wireguard  366 Jul  3 17:38 wg0.conf

All good here, though maybe I should block the last `r` in a next release.

> systemctl restart wireguard_ui
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.10.10.0/24 dev wg0
[#] ip link set mtu 1450 up dev wg0
[#]

Perfect. That means the interface was down and the command brought it up online.

> then, prepending sudo, it worked

No error message but still 502 error?

> No journal files were opened due to insufficient permissions.

A prepended `sudo` would make it work. ;) Though I guess that the earlier `chown` would make it work. Restart the service again, and share the output of `sudo journalctl -xe` again if it fails or if you get 502 error again.

**Comment by xplosionmind** [comment]
> I may express annoyment though, but it is not directed at you or other users. I am by no means an expert on WireGuard and networking, so testing and debugging is pretty much trial and error. And it can get very frustrating.

I understand… I just wish I could do more… Thank you very much for your support. It means a lot.

<br />

> OK so, maybe the binary not belonging to the `wireguard` user is an issue. Try `sudo chown wireguard:wireguard /opt/yunohost/wireguard/wireguard_ui`

The working path is `sudo chown wireguard:wireguard /opt/yunohost/wireguard/wireguard-ui`: not an underscore but a dash in the `wireguard-ui` file. That pointed out, I changed permissions but unfortunately the issue is still happening, even after rebooting the server and `systemctl`:

<img width="1439" alt="Screenshot 2021-07-04 at 7 28 25 PM" src="https://user-images.githubusercontent.com/42862428/124394079-3f29dc80-dced-11eb-9463-4f4f81a0f79c.png">

<br />

By running `sudo journalctl -xe` I get:

```
Jul 04 19:29:23 server.tommi.space systemd[18110]: wireguard_ui.service: Failed
-- Subject: Process /opt/yunohost/wireguard/wireguard-ui could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The process /opt/yunohost/wireguard/wireguard-ui could not be executed and fa
--
-- The error number returned by this process is ERRNO.
Jul 04 19:29:23 server.tommi.space systemd[1]: wireguard_ui.service: Main proces
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit wireguard_ui.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 200.
Jul 04 19:29:23 server.tommi.space systemd[1]: wireguard_ui.service: Failed with
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit wireguard_ui.service has entered the 'failed' state with result 'exi
Jul 04 19:29:33 server.tommi.space sudo[18115]:    admin : TTY=pts/0 ; PWD=/home
Jul 04 19:29:33 server.tommi.space sudo[18115]: pam_unix(sudo:session): session
```

**Comment by tituspijean** [comment]
Can you try running `sudo -u wireguard /opt/yunohost/wireguard/wireguard-ui`?

**Comment by xplosionmind** [comment]
```
sudo -u wireguard /opt/yunohost/wireguard/wireguard-ui
[sudo] password for admin:
sudo: /opt/yunohost/wireguard/wireguard-ui: command not found
```

without `-u` it happens the same thing.

**Comment by tituspijean** [comment]
Issue found and fixed in #27. Feel free to reopen if needed.

**Comment by xplosionmind** [comment]
How long until the update gets to my Yunohost instance?

**Comment by tituspijean** [comment]
Right now, the automated tests are not working (an obscure issue with the Linux kernel headers of container used for testing).
You will need to force the installation: `yunohost app install https://github.com/YunoHost-Apps/wireguard_ynh --force`
