### ISSUE TITLE
App is level 0

### ISSUE THREAD

**Issue by SimonMellerin** [YunoHost-Apps/wireguard_ynh#30]
This app seems to be at level 0 since the beginning of july.

https://dash.yunohost.org/appci/app/wireguard

Is it still maintained & stable ?

Thanks
Simon

**Comment by tituspijean** [comment]
Level 0 is due to a bug in our CI, which is still to be resolved. The app is working well on my side, install it at your own risk.

**Comment by SimonMellerin** [comment]
Ok tanks

**Comment by tituspijean** [comment]
I will leave it open since this is an ongoing issue. 🙂

**Comment by tituspijean** [comment]
Looks like it is solved.

**Comment by prog-amateur2** [comment]
Hello, I see on the Yunohost catalog that the app is considered as "broken". Do you know if it is related to this issue ? If this issue is closed, do you think we can use Wireguard safely ? Thank you !!!

**Comment by tituspijean** [comment]
Ha, it looks like it is solved on the developers' CI (https://ci-apps-dev.yunohost.org/ci/job/3090), not the main one (https://ci-apps.yunohost.org/ci/job/3038). Anyways, my first comment above still stands, the app works. ;)

You can install the current testing version, it includes some additional safety : `yunohost app install https://github.com/YunoHost-Apps/wireguard_ynh/tree/testing --force`

**Comment by prog-amateur2** [comment]
Thank you very much tituspijean !
