### ISSUE TITLE
How to connect to the UI - Documentation leads to 404

### ISSUE THREAD

**Issue by prog-amateur2** [YunoHost-Apps/wireguard_ynh#35]
### Describe the bug

Hello, I am a beginner in wireguard. I have successfully installed it through Yunohost app store. When I try to connect to wireguard from URL (I imagine it leads to the Wireguard Web UI), I have a certificate alert page. And I can't add an exception. 

Maybe I do something wrong, so I try to connect to the wireguard's yunohost documentation but [it shows an 404 error page](https://yunohost.org/app_wireguard).  

Could you please explain me what did I wrong and also why the documentation is not available ? 

Thank you very much for your help !

### Context

- Hardware: Old laptop or computer
- YunoHost version: 4.2.8
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes 
  - If yes, please explain: I have installed Pi-Hole (from Yunohost app store) and unbound from the Debian command line through SSH (everything successful). 
- Using, or trying to install package version/branch: 0.2.7~ynh8
- If upgrading, current package version: no

### Steps to reproduce

Go to `https://wireguard.domain.com` : it shows a certificate alert page without possibility to add exception : 

![](https://i.ibb.co/V3JdXKC/Capture-d-cran-de-2021-09-19-14-10-20.png)

### Expected behavior

I shall connect to the Wireguard UI and access to the documentation. 

### Logs

![](https://i.ibb.co/jvzs6z7/Capture-d-cran-de-2021-09-19-14-35-17.png)

After diagnosis, l can see that port 8098 needed for service `wg-quick@wg0` is not enabled for outside. Do I have to open it mandatory or not ?

**Comment by tituspijean** [comment]
* Sorry about the missing documentation, I should write one someday...
* I think you need to create a Let's Encrypt certificate for your wireguard domain.
* Regarding port 8098, if that's the port dedicated to WireGuard (not its UI), then yes, you need it opened. That's how the connection is made to the VPN.

**Comment by prog-amateur2** [comment]
Hello, thank you very much for your kind help. I have applied your advises : 
- doc : I understand you need time to do it so I don't bohter with it. By the way, do you know where I can find a tutorial to easily setup wireguard please ? 
- let's encrypt has been installed and now I can connect to the wireguard UI
- port has been opened and I can also connect to the UI, that's a good news (but as your link, I still can see the error message in the diagnosis tool). 

To me, I can close this issue as I shall follow the issue https://github.com/YunoHost-Apps/wireguard_ynh/issues/32 regarding the port notification. 

Again, thank you for having helped me.
