### ISSUE TITLE
Connection OK but no internet

### ISSUE THREAD

**Issue by sy6sy2** [YunoHost-Apps/wireguard_ynh#36]
### Describe the bug

I installed the app with testing branch and also add the post up and post down command, I am able to connect to the VPN but when I'm connection I have no internet connection.

Thank you

### Context

- Hardware: OVH VPS
- YunoHost version: 4.2.8.3
- I have access to my server: SSH
- Using, or trying to install package version/branch: testing

### Logs

```
Oct 07 21:43:36 cyber-detect.org systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Oct 07 21:43:36 cyber-detect.org wg-quick[3487]: [#] ip link add wg0 type wireguard
Oct 07 21:43:36 cyber-detect.org wg-quick[3487]: [#] wg setconf wg0 /dev/fd/63
Oct 07 21:43:36 cyber-detect.org wg-quick[3487]: [#] ip -4 address add 10.10.10.0/24 dev wg0
Oct 07 21:43:36 cyber-detect.org wg-quick[3487]: [#] ip link set mtu 1450 up dev wg0
Oct 07 21:43:36 cyber-detect.org wg-quick[3487]: [#]
Oct 07 21:43:36 cyber-detect.org systemd[1]: Started WireGuard via wg-quick(8) for wg0.
```

**Comment by tituspijean** [comment]
Had you enabled port forwarding? You can try upgrading, it does that automagically now.
