### ISSUE TITLE
Use dkms module instead of installing a second kernel ?

### ISSUE THREAD

**Issue by tytan652** [YunoHost-Apps/wireguard_ynh#4]
Hi, I'm just asking why don't you use wireguard dkms module in buster-backport, instead of using buster-backport kernel ?
This way we keep the LTS kernel, we may still need a reboot anyway.
It will need to set YunoHost 4 as minimum version for Buster

**Comment by tituspijean** [comment]
Hi!

There is no particular reason for not using DKMS right now. This first version of the app was merely as a proof of "it can work on YunoHost". Any improvement is welcome. ;)
