### ISSUE TITLE
Application is reported as broken in Yunohost 4.3.4.1

### ISSUE THREAD

**Issue by prog-amateur2** [YunoHost-Apps/wireguard_ynh#43]
Hello on Yunohost 4.3.4.1, on a x86_64 device, after each diagnostic, I can see the following message : 

```
A problem has been detected for the application Wireguard

    This application is currently reported as broken in the YunoHost application catalog. This may be a temporary problem. Until the maintainers attempt to resolve the issue, updating of this application is disabled.

```

This message happens for quite a long time now, so I would like to know if you still maintain this app, and if possible, if you could fix this issue please ? 

Thank you very much

**Comment by tituspijean** [comment]
I do still maintain the app. It is a tad complex one though, so I can never guarantee swift fixes.
However, as the warning tells you, it only prevents upgrades, and does not impede its current use.
Thank you for your patience and understanding.
