### ISSUE TITLE
Status page is not working, requires root

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/wireguard_ynh#46]
### Describe the bug

Status page in the UI requires the webapp to be run as `root`. It should be avoided, this issue is open as both a notification for users and investigation thread to find alternative solutions.

### Context

Package version > 0.3.2~ynh1

**Comment by manuc66** [comment]
Just to share the actual display : 
![image](https://github.com/YunoHost-Apps/wireguard_ynh/assets/5827164/1849a593-755b-4417-a81c-18db85e0875c)

**Comment by TSGeek** [comment]
Hi,
it's a capability that the service is missing to query the devices.
A workaround is to add these lines to the wireguard_ui service :
`CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW
AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW`

I'm doing a PR for that.

Regards.
