### ISSUE TITLE
App not working after update

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/wireguard_ynh#59]
### Describe the bug

COnnection to the internet does not work when tunnel is enabled, after update to 0.3.6~ynh2 (it worked in 0.3.6~ynh1.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: *0.3.6~ynh2*

### Steps to reproduce

- Update Wireguard from the web interface
- Not working
- Remove Wireguard from the web interface
- Install Wireguard via SSH on CLI
- reconfiguring everything (the post-up script suggested by @tituspijean in #28 cannot be found in the README anymore, so I did not set it)
- still not working

### Expected behavior

*Connection should be working*

### Logs

- [Upgrade log](https://paste.yunohost.org/raw/gamomuleji)
- [App removal log](https://paste.yunohost.org/raw/uzesihijay)
- [Re-installation log](https://paste.yunohost.org/raw/hanebuboha)

**Comment by tituspijean** [comment]
Thank you for your report! Are the post up and post down scripts actually set in the web interface for WireGuard? (I removed it from the README because they are supposed to be automagically set now) If so, can you share them, along with the output of `ip route`?

**Comment by xplosionmind** [comment]
```
admin@server:~$ ip route
default via 167.86.82.1 dev eth0 onlink
10.10.10.0/24 dev wg0 proto kernel scope link src 10.10.10.0
167.86.82.0/24 via 167.86.82.1 dev eth0
```

Post Up Script:
```
iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FORWARD -i %i -j ACCEPT; ip6tables -A FORWARD -o %i -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip link set multicast on dev %i
```

Post Down Script:
```
iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; ip6tables -D FORWARD -i %i -j ACCEPT; ip6tables -D FORWARD -o %i -j ACCEPT; ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```

**Comment by tituspijean** [comment]
Sorry for the very late answer.

I just realized that the route to `0.0.0.0/0` or `::/0` is not set. Can you share your `/etc/wireguard/wg0.conf`, and removing any personal information?
Did you click on `Apply config` ?

**Comment by tituspijean** [comment]
Closing as stale.
