### ISSUE TITLE
Installation fails because "Unable to install dependencies"

### ISSUE THREAD

**Issue by Flashpok** [YunoHost-Apps/wireguard_ynh#62]
### Describe the bug

Installation fails because "Unable to install dependencies"

### Context

- Hardware:Internet Cube with VPN
- YunoHost version: 4.3.6.3 (stable). Kernel unlocked and upgraded
- I have access to my server: *Through SSH & through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no

### Steps to reproduce

- I first tried with web administration-> not working and same error with the "testing" cli installation : 
```
206291 WARNING The following packages have unmet dependencies:
206298 WARNING  wireguard : Depends: wireguard-tools (>= 1.0.20210223-1~bpo10+1) but 1.0.20200827-1~bpo10+1 is to be installed
206302 WARNING  wireguard-dkms : Depends: dkms (>= 2.1.0.0) but it is not going to be installed
206306 DEBUG + ynh_die '--message=Unable to install dependencies'
```

### Logs
https://paste.yunohost.org/raw/etepuveyen

I hope you can help me !
Thank you very much !

**Comment by tituspijean** [comment]
Hello, can you try the testing version with the following command?

`sudo yunohost app upgrade wireguard -u https://github.com/YunoHost-Apps/wireguard_ynh/tree/testing`

**Comment by Flashpok** [comment]
Hi @tituspijean 
Thank you for your help !

I tried it, but same error message : 

`388885 WARNING The following packages have unmet dependencies:
388888 WARNING  wireguard : Depends: wireguard-tools (>= 1.0.20210223-1~bpo10+1) but 1.0.20200827-1~bpo10+1 is to be installed
388893 DEBUG + ynh_die '--message=Unable to install dependencies'
388902 DEBUG + local legacy_args=mc
388913 DEBUG + args_array=([m]=message= [c]=ret_code=)
388917 DEBUG + local -A args_array
388925 DEBUG + local message
388930 DEBUG + local ret_code
388943 DEBUG + ynh_handle_getopts_args '--message=Unable to install dependencies'
388945 DEBUG + set +o xtrace
389148 DEBUG + ret_code=1
389151 DEBUG + echo 'Unable to install dependencies'
389153 DEBUG + exit 1
389159 WARNING Unable to install dependencies
389163 DEBUG + ynh_exit_properly
`

**Comment by Flashpok** [comment]
un petit up.
Que puis-je mettre à jour et comment pour installer les dépendances qui refusent de s'installer pendant l'install ?
merci ;-)

**Comment by tituspijean** [comment]
Closing as stale. Feel free to reopen if the problem is still here.
