### ISSUE TITLE
`/etc/wireguard/wg0.conf' does not exist

### ISSUE THREAD

**Issue by amannott** [YunoHost-Apps/wireguard_ynh#65]
Describe the bug:
I tried a several times to install, but wireguard does not start. The log says: "/etc/wireguard/wg0.conf' does not exist"

Context
VPS from Contabo 
Architecture is kvm amd64 with Linux-Kernel 4.19.0-20-amd64 under Debian 10.12
YunoHost 4.3.6.3 (stable) 
I have access to my server: through SSH & through the webadmin
Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no

The log says always:

Apr 22 18:18:45 systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Apr 22 18:18:45 wg-quick[3817]: wg-quick: `/etc/wireguard/wg0.conf' does not exist
Apr 22 18:18:45 systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 18:18:45 systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
Apr 22 18:18:45 systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.

**Comment by tituspijean** [comment]
@hanswundersam `W: Possible missing firmware /lib/firmware/bnx2x/bnx2x-e2-7.13.15.0.fw for module bnx2x` looks like an unrelated issue. If you accept non-free dependencies on your server, you might be able to fix it with:

```
sudo su
echo "deb http://deb.debian.org/debian bullseye non-free" > /etc/apt/sources.list.d/non-free.list
apt update
```

Onto your WireGuard issue... can you try running `sudo wg-quick up wg0`. Report the output.

**Comment by hanswundersam** [comment]
Thanks a lot for your quick reply @tituspijean. Here is the output:

```
admin@vps:~$ sudo wg-quick up wg0
[#] ip link add wg0 type wireguard
RTNETLINK answers: Operation not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
```

**Comment by tituspijean** [comment]
Can you try manually installing wireguard and rebooting your server?

`sudo apt install wireguard`

**Comment by hanswundersam** [comment]
The wireguard package seems to already be installed (output translated into English):

```
admin@vps:~$ sudo apt install wireguard
Reading package list… Done
Calculating dependencies… Done
Reading status information… Done
The latest version of wireguard is already installed (1.0.20210223-1).
wireguard has been marked as manually installed.
```

**Comment by tituspijean** [comment]
Closing as stale.
