### ISSUE TITLE
wg-quick@wg0 don't start

### ISSUE THREAD

**Issue by sirmelonchen** [YunoHost-Apps/wireguard_ynh#68]
My Wireguard installation won't start. My log is below the text. I've tried installing a different kernel, but that didn't help. I don't know what to do anymore. Please help.

Log: https://paste.yunohost.org/noqilaneqo

**Comment by Tagadda** [comment]
Hi ~ Can you share the install log too ?

**Comment by Seelachsfilet** [comment]
> > > Hi ~ Can you share the install log too ?
> > 
> > Hi ~ where can I find the install logs? I'm new to yunohost :)
> 
> In your webadmin: Tools > Logs.
> Select your install attempt and use the "Share with YunoPaste" button.

https://paste.yunohost.org/ugitavovuj

**Comment by tituspijean** [comment]
Can you confirm you rebooted the server, and if so, what's the output of `sudo dkms status` ?

**Comment by kazukyakayashi** [comment]
I have same problem after update.

``` 
sudo dkms status
sudo: dkms: command not found
```

**Comment by tituspijean** [comment]
Closing as stale. Sorry if I could not help you out.
