### ISSUE TITLE
suggestion: a way to use custom/existing public key for clients

### ISSUE THREAD

**Issue by azbulutlu** [YunoHost-Apps/wireguard_ynh#76]
### Describe the bug
I am not sure if this is the right place for this suggestion so apologies in advance if it is not. 

When creating a new key the private/public key pair for the client is stored on server. While this is a good convenience feature for beginner user, it is also a security issue. Would be good to have an advanced option create a client config with an existing custom key

### Context

- Hardware: VPS
- YunoHost version: 11.0.11
- I have access to my server: Through ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Steps to reproduce

- When creating a new config only way is to store client private key on server.
- 
### Expected behavior

An option to create a client config with an existing client public key. 
The client config file downloaded would either require a manual edit before using or the option to download config files for this option would be disabled altogether.
Clear indication that this is an advanced feature.

**Comment by tituspijean** [comment]
That's rather a matter for the upstream app. Otherwise you are welcome to tinker in your app files, but you will not get support from here, sorry.
