### ISSUE TITLE
update to 0.5.2?

### ISSUE THREAD

**Issue by 32bitx64bit** [YunoHost-Apps/wireguard_ynh#85]
When will this app get updated? If ever.

**Comment by tituspijean** [comment]
As of today, the latest available version for the upsteam app is only [v0.5.1](https://github.com/ngoduykhanh/wireguard-ui/releases).

**Comment by 32bitx64bit** [comment]
Whoops typo on my part, will this ever be updated to the latest version of 0.5.1?

**Comment by tituspijean** [comment]
v0.5.0 just got merged to the main branch. We'll get the autoupdate testing to v0.5.1 tomorrow hopefully.
