### ISSUE TITLE
Lower default MTU to 1400 (instead of 1450)

### ISSUE THREAD

**Issue by jcn50** [YunoHost-Apps/wireguard_ynh#97]
I tried on 2x different servers in 2x different countries, and nothing was working until I lowered the default MTU to **1400** (xDSL). You should update the default value to 1400 so that it works for everyone. Thanks!

**Comment by tituspijean** [comment]
Hello, thank you for your feedback. This setting is highly dependent on the connection type. It is fine with my own, for example. This is documented within the web UI, right next to the MTU global setting, and I took the liberty to add a warning in the ADMIN.md file of the app.
